version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/tjhop/prometheus-mcp-server/internal/version.BuildDate={{ .CommitDate }}
      - -X github.com/tjhop/prometheus-mcp-server/internal/version.Version={{ .Version }}
      - -X github.com/tjhop/prometheus-mcp-server/internal/version.Commit={{ .Commit }}
    binary: prometheus-mcp-server
    main: './cmd/prometheus-mcp-server'
gomod:
  proxy: false
dockers_v2:
  - images:
      - "ghcr.io/tjhop/{{.ProjectName}}"
    tags:
      - "{{.Version}}"
      - "v{{.Version}}"
      - "latest"
    labels:
      "org.opencontainers.image.description": "Prometheus MCP Server"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.licenses": "Apache-2.0"
      "io.modelcontextprotocol.server.name": "io.github.tjhop/{{.ProjectName}}"
    platforms:
      - linux/amd64
      - linux/arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
nfpms:
  - package_name: 'prometheus-mcp-server'
    homepage: 'https://github.com/tjhop/prometheus-mcp-server'
    maintainer: 'TJ Hoplock <t.hoplock@gmail.com>'
    description: 'Prometheus MCP Server'
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    contents:
      - src: ./README.md
        dst: /usr/share/doc/tjhop/prometheus-mcp-server/README.md
      - src: ./packaging/systemd/prometheus-mcp-server.service
        dst: /lib/systemd/system/prometheus-mcp-server.service
        type: config
        file_info:
          mode: 0644
          owner: root
          group: root
universal_binaries:
  - replace: true
archives:
  - files:
    - LICENSE*
    - README*
    - docs/*
    - documentation/*
    - examples/*
    - packaging/systemd/prometheus-mcp-server.service
mcp:
  github:
    name: "io.github.tjhop/{{.ProjectName}}"
    title: "Prometheus MCP Server"
    description: "An API-complete MCP server to manage Prometheus-compatible backends."
    homepage: "{{.GitURL}}"
    repository:
      source: "github"
      url: "{{.GitURL}}"
    auth:
      type: 'github{{- if isEnvSet "GITHUB_ACTIONS" }}-oidc{{ end -}}'
      token: "{{ .Env.GITHUB_TOKEN }}"
    packages:
      - registry_type: oci
        identifier: "ghcr.io/tjhop/{{.ProjectName}}:{{ .Version }}"
        transport:
          type: stdio
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request'
      - '^ci(?:\(\w+\))?\!?:'
      - '^docs(?:\(\w+\))?\!?:'
      - '^test(?:\(\w+\))?\!?:'
      - '^style(?:\(\w+\))?\!?:'
  groups:
    - title: "New Features And Changes"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Other Changes"
      order: 999
