apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-mcp-server
  namespace: default
  labels:
    app: prometheus-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-mcp-server
  template:
    metadata:
      labels:
        app: prometheus-mcp-server
    spec:
      containers:
      - name: prometheus-mcp-server
        image: ghcr.io/tjhop/prometheus-mcp-server:latest
        args: 
          - '--prometheus.url=http://prometheus-service.prometheus.svc:9090' # set your prometheus url here
          - '--mcp.transport=http'
          - '--web.listen-address=:8080'
          - '--log.level=info'
        imagePullPolicy: Always
        ports:
        - containerPort: 8080