name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC authentication to publish to MCP registry
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
      - name: Go Preflight Tests
        run: |
          go mod tidy
          go test -v ./...
      - name: Docker Login (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install MCP Publisher
        run: |
          git clone --quiet https://github.com/modelcontextprotocol/registry publisher-repo
          cd publisher-repo && make publisher > /dev/null && cd ..
          cp publisher-repo/bin/mcp-publisher . && chmod +x mcp-publisher
      - name: Update server.json version
        run: |
          TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          sed -i "s/\${VERSION}/$TAG_VERSION/g" server.json
          echo "Version: $TAG_VERSION"
      - name: Validate MCP registry server configuration
        run: |
          python3 -m json.tool server.json > /dev/null && echo "Configuration valid" || exit 1
      - name: Display final server.json
        run: |
          echo "Final server.json contents:"
          cat server.json
      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc
      - name: Publish to MCP Registry
        run: ./mcp-publisher publish
